### ISSUE TITLE
Change repo name to insiter.github.io

### ISSUE THREAD

**Issue by iagodahlem** [insiter/insiter.io#9]
Then we don't need to use `gh-pages` branch to deploy, just the `master` branch.

What do you guys think about that?

**Comment by fabricionaweb** [comment]
In this case, we can leave the source code in the `master` and only the dist files in `gh-pages` branch.
Because GitHub looks for the `index.html` (and relative assets) in the root directory of the repository.
And I don't think that leaving all the files in one branch wouldn't be organized.

**Comment by iagodahlem** [comment]
Ok then. You convinced me.
